field_configs = {
    % {field_name, Output_H5fieldName, latex_label}
    'wT_p',  'wT_p', '(\dot{\omega}_T)_p';
    'wT',  'wT_r', '(\dot{\omega}_T^{*}';
    'Heatrelease',  'wTn', '\dot{\omega}_{T,n}';
    'Temperature',  'T', 'T';
    'density',  'rho', '\rho';
    'CH4',  'CH4', 'Y_{CH4}';
%     'CH2O',  'CH2O', 'Y_{CH2O}';
%     'CH3',  'CH3', 'Y_{CH3}';
%     'CO',  'CO', 'Y_{CO}';
%     'H',  'H', 'Y_{H}';
%     'H2',  'H2', 'Y_{H_2}';
%     'HO2',  'HO2', 'Y_{HO_2}';
    'O2',  'O2', 'Y_{O_2}';
%     'O',  'O', 'Y_{O}';
%     'OH',  'OH', 'Y_{OH}';
    'CO2',  'CO2', 'Y_{CO2}';
    'H2O',  'H2O', 'Y_{H2O}';
%     'N2',  'N2', 'Y_{N_2}';
    'SYm_CH4',  'wCH4', '\dot{\omega}_{CH_4}';
%     'SYm_CH2O',  'wCH2O', '\dot{\omega}_{CH_2O}';
%     'SYm_CH3',  'wCH3', '\dot{\omega}_{CH_3}';
%     'SYm_CO',  'wCO', '\dot{\omega}_{CO}';
%     'SYm_H',  'wH', '\dot{\omega}_{H}';
%     'SYm_H2',  'wH2', '\dot{\omega}_{H_2}';
%     'SYm_HO2',  'wHO2', '\dot{\omega}_{HO2}';
    'SYm_O2',  'wO2', '\dot{\omega}_{O_2}';
%     'SYm_O',  'wO', '\dot{\omega}_{O}';
%     'SYm_OH',  'wOH', '\dot{\omega}_{OH}';
    'SYm_CO2',  'wCO2', '\dot{\omega}_{CO_2}';
    'SYm_H2O',  'wH2O', '\dot{\omega}_{H_2O}';
%     'SYm_N2',  'wN2', '\dot{\omega}_{N_2}';
};